### ISSUE TITLE
Spider alive after death

### ISSUE THREAD

**Issue by asyouw1sh** [Mud-xyz/evermore-bugs#24]
**Describe the bug**
If you kill a spider and level up from it the spider stays persistent despite not being on map.

**To Reproduce**
1. Logged into basalisk map with caster char (this may also work with melee did not test)
2. Level up a few times and then go fight a spider when you are about to level up (usually you want to be within 100xp of lvl up)
3. Once you kill the spider and level up you will notice that the spider continues attacking you. The spider stays persistent for the remainder of the session and will attack as soon as you enter its room. You cannot attack the spider back or interact with it aside from fleeing.

**Expected behavior**
Spider should die and be gone

**Screenshots or Output Logs**

![spiderded](https://user-images.githubusercontent.com/74503834/157800361-be9a71a1-d0f2-4131-8051-ea63e73185bb.PNG)

**Additional context**
What is the Match ID for the match? 933bf4c0-8fd0-4932-b817-23118921db59
Roughly when did this occur (with timezone)? 11pmest
Which browser were you using? firefox
Do you have any special hardware or software running? no

I noticed that this happens only with spiders. The slime molds and basilisks are not effected. I wonder if this is because both the slimes and basilisks wander while the spiders do not. Just an observation.

**Comment by gvanderest** [comment]
Based on some exceptions/bugs seen in the logs, this could very easily be caused by a small logic error in multiple parts, causing further logic to not execute (like the actual removal of the spider).

Based on the current echos displayed, it would appear that the full experience+leveling gain was computed.. I'll trace the code a bit to see if I can isolate where this could have occurred.
