### ISSUE TITLE
Targeting Issue 

### ISSUE THREAD

**Issue by asyouw1sh** [Mud-xyz/evermore-bugs#8]
**Describe the bug**
After death target highlight goes away, but ally is still targeted. When trying to select ally again it highlights but does not target in game, instead it targets self. Attempting to select again does not remove the highlight, but still heals self regardless.

**To Reproduce**
1. Select an ally in arcade mode
2. Let ally die
3. Meet back up with ally and attempt to heal them. It will heal self instead.
4. Go target the enemy lord and then return to the ally without targeting them and attempt to heal. It will heal them even though they are not selected.

**Expected behavior**
When selecting an ally in arcade mode they should be targeted in game. If the ally is already targeted and is clicked again I believe the normal behavior was to target self.

**Screenshots or Output Logs**
Unfortunately I did not capture anything as I thought I was recording...

**Additional context**
Penguin mentioned that the index may be off by 1 due to assigning a new id after death.

**Comment by ratacat** [comment]
Thank you @asyouw1sh for the very thorough report. That's extremely helpful. So there are two things on that I can tell. I'll start with 4).

4) Our targeting algorithm keeps track of `lastAllyTarget` and `lastEnemyTarget`. So that if you heal an ally, then use a skill on an enemy. But then hit 'heal' again, it will automatically target your last ally. That's what happened in this situation.

1-3) This is actually also expected, targeting is meant to not persist past death. So anyone you have targeted will become an invalid target after they die. This is for a number of reasons, but one of which being that you can't just leave your target on a specific enemy throughout the whole game.
